#!/usr/bin/env bash

WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TOOLS_JAR="$WORKING_DIR/libs/tools.jar"

CLASSPATH="$TOOLS_JAR"
CLASSPATH="$WORKING_DIR/libs/kotlin-reflect.jar:$CLASSPATH"
CLASSPATH="$WORKING_DIR/libs/kotlin-stdlib.jar:$CLASSPATH"
CLASSPATH="$WORKING_DIR/libs/com.squareup.kotlinpoet-0.5.0.jar:$CLASSPATH"

SAMPLE_CLASSPATH="$CLASSPATH:$WORKING_DIR/ap/build/output/my-ap-lib.jar"

JAVAC_CLASSPATH="$SAMPLE_CLASSPATH"
JAVAC_CLASSPATH="$JAVAC_CLASSPATH:$WORKING_DIR/sample/build/output"

ANNOTATION_PROCESSOR="$WORKING_DIR/libs/kotlin-annotation-processing.jar"

# Kapt Plugin specific
SOURCES="build/sources"
CLASSES="build/classes"
STUBS="build/stubs"
INCREMENTAL_DATA="build/incremental"
LIGHT_ANALYSIS="true"
CORRECT_ERROR_TYPES="false"
VERBOSE="true"
EMPTY_MAP="rO0ABXcEAAAAAA==" # encoded empty map
GENERATED_DIR_MAP="rO0ABXdtAAAAAQAVa2FwdC5rb3RsaW4uZ2VuZXJhdGVkAFAvVXNlcnMvdGhhbGVzbWFjaGFkby9Eb2N1bWVudHMvUHJvamVjdHMvcGVyc29uYWwva2FwdC1jbGkvc2FtcGxlL2J1aWxkL2dlbmVyYXRlZA==" # kapt.kotlin.generated to sample/build/output
