#!/usr/bin/env bash

WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf $WORKING_DIR/ap-kt/build/output/*
rm -rf $WORKING_DIR/ap-java/build/output/*
rm -rf $WORKING_DIR/sample/build/output/*
rm -rf $WORKING_DIR/sample/build/generated/*
rm -rf $WORKING_DIR/build/classes/*
rm -rf $WORKING_DIR/build/incremental/*
rm -rf $WORKING_DIR/build/output/*
rm -rf $WORKING_DIR/build/sources/*
rm -rf $WORKING_DIR/build/stubs/*
